version: "3.2"

services:
#MariaDB Container
  mariadb:
    image: mariadb:10
    container_name: mariadb
    hostname: mariadb
    volumes:
      - ./mysql:/var/lib/mysql
    env_file:
      - ./mariadb.env
    restart: always

#GLPI Container
  glpi:
    image: diouxx/glpi
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./www-glpi:/var/www/html/glpi
    env_file:
      - ./glpi.env
    restart: always
